- name: Setup ash Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/bastion_setup.txt

    - name: Import VPC setup Variable
      include_vars: vars/output_vars

    - name: Create ash ec2 key
      ec2_key:
        name: ash-key
        region: "{{region}}"
      register: key_out


    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create Security Group for bastion host
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port within security group
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out

    - name: Creating Bastion Host
      ec2:
        key_name: ash-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          Project: ash
          Owner: Aswanth Ramamoorthy
          # To create only one Bastion Host
        exact_count: 1
        count_tag:
          Name: "Bastion_host"
          Project: ash
          Owner: Aswanth Ramamoorthy
        group_id: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out